// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA74xIvJXsOvTlv3_TlWoQUfiqDqZaNiTU',
    appId: '1:397749779909:android:7dc1cc32fe7c4b944e9fac',
    messagingSenderId: '397749779909',
    projectId: 'al-khalifa-food-app',
    storageBucket: 'al-khalifa-food-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBApRyWKMwbFAfVkHc4NkHaDGKSN8OtYLU',
    appId: '1:397749779909:ios:773a1ac5d820f0bc4e9fac',
    messagingSenderId: '397749779909',
    projectId: 'al-khalifa-food-app',
    storageBucket: 'al-khalifa-food-app.firebasestorage.app',
    iosClientId: '397749779909-broj3is3bka6ut7r3iikk4qhdr2kch52.apps.googleusercontent.com',
    iosBundleId: 'com.alkhalifa.alKhalifa',
  );
}
